spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: dawn-web
  # 虚拟线程配置
  threads:
    virtual:
      enabled: true
  # 优雅关闭配置
  lifecycle:
    timeout-per-shutdown-phase: 30s

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml

# 服务器配置
server:
  # 优雅关闭配置
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
