spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: dawn-project
  # 虚拟线程配置
  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml
